/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum020726;

/**
 *
 * @author Khairunnisah
 */
public class MenuMinuman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMinuman.class.getName());

    /**
     * Creates new form MenuMinuman
     */
    public MenuMinuman() {
        initComponents();
        txtAir.setEditable(false);
        txtEs.setEditable(false);
        txtKopi.setEditable(false);
        txtJus.setEditable(false);
        txtTea.setEditable(false);
        txtLemon.setEditable(false);
        txtCappuccino.setEditable(false);

        txtTotalAir.setEditable(false);
        txtTotalEs.setEditable(false);
        txtTotalKopi.setEditable(false);
        txtTotalJus.setEditable(false);
        txtTotalTea.setEditable(false);
        txtTotalLemon.setEditable(false);
        txtTotalCappuccino.setEditable(false);

        txtTotal.setEditable(false);

    }
    private MenuUtama utama;
    public MenuMinuman(MenuUtama utama){
        this.utama=utama;
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkAir = new javax.swing.JCheckBox();
        chkEs = new javax.swing.JCheckBox();
        chkKopi = new javax.swing.JCheckBox();
        chkJus = new javax.swing.JCheckBox();
        chkTea = new javax.swing.JCheckBox();
        chkLemon = new javax.swing.JCheckBox();
        chkCappuccino = new javax.swing.JCheckBox();
        txtAir = new javax.swing.JTextField();
        txtEs = new javax.swing.JTextField();
        txtKopi = new javax.swing.JTextField();
        txtJus = new javax.swing.JTextField();
        txtTea = new javax.swing.JTextField();
        txtLemon = new javax.swing.JTextField();
        txtCappuccino = new javax.swing.JTextField();
        cbLemon = new javax.swing.JComboBox<>();
        cbCappuccino = new javax.swing.JComboBox<>();
        cbTea = new javax.swing.JComboBox<>();
        cbJus = new javax.swing.JComboBox<>();
        cbKopi = new javax.swing.JComboBox<>();
        cbAir = new javax.swing.JComboBox<>();
        cbEs = new javax.swing.JComboBox<>();
        txtTotalAir = new javax.swing.JTextField();
        txtTotalEs = new javax.swing.JTextField();
        txtTotalCappuccino = new javax.swing.JTextField();
        txtTotalLemon = new javax.swing.JTextField();
        txtTotalTea = new javax.swing.JTextField();
        txtTotalJus = new javax.swing.JTextField();
        txtTotalKopi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PILIHAN MENU MINUMAN");

        chkAir.setText("Air Mineral");
        chkAir.addActionListener(this::chkAirActionPerformed);

        chkEs.setText("Es Teh manis");
        chkEs.addActionListener(this::chkEsActionPerformed);

        chkKopi.setText("Kopi Susu");
        chkKopi.addActionListener(this::chkKopiActionPerformed);

        chkJus.setText("Jus Mangga");
        chkJus.addActionListener(this::chkJusActionPerformed);

        chkTea.setText("Thai Tea");
        chkTea.addActionListener(this::chkTeaActionPerformed);

        chkLemon.setText("Lemon Tea");
        chkLemon.addActionListener(this::chkLemonActionPerformed);

        chkCappuccino.setText("Cappuccino");
        chkCappuccino.addActionListener(this::chkCappuccinoActionPerformed);

        txtAir.setText("0");

        txtEs.setText("0");

        txtKopi.setText("0");
        txtKopi.addActionListener(this::txtKopiActionPerformed);

        txtJus.setText("0");

        txtTea.setText("0");

        txtLemon.setText("0");

        txtCappuccino.setText("0");

        cbLemon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbLemon.addActionListener(this::cbLemonActionPerformed);

        cbCappuccino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbCappuccino.addActionListener(this::cbCappuccinoActionPerformed);

        cbTea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTea.addActionListener(this::cbTeaActionPerformed);

        cbJus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJus.addActionListener(this::cbJusActionPerformed);

        cbKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbKopi.addActionListener(this::cbKopiActionPerformed);

        cbAir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAir.addActionListener(this::cbAirActionPerformed);

        cbEs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEs.addActionListener(this::cbEsActionPerformed);

        txtTotalAir.setText("0");

        txtTotalEs.setText("0");

        txtTotalCappuccino.setText("0");

        txtTotalLemon.setText("0");
        txtTotalLemon.addActionListener(this::txtTotalLemonActionPerformed);

        txtTotalTea.setText("0");

        txtTotalJus.setText("0");

        txtTotalKopi.setText("0");

        jLabel2.setText("Total");

        txtTotal.setText("0");
        txtTotal.addActionListener(this::txtTotalActionPerformed);

        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(chkEs)
                                    .addComponent(chkAir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkKopi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkJus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(chkTea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkLemon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkCappuccino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLemon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTea, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbLemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalAir, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txtTotalCappuccino)
                            .addComponent(txtTotalLemon)
                            .addComponent(txtTotalTea)
                            .addComponent(txtTotalJus)
                            .addComponent(txtTotalKopi)
                            .addComponent(txtTotalEs)
                            .addComponent(txtTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnTotal)
                        .addGap(53, 53, 53)
                        .addComponent(btnReset)
                        .addGap(71, 71, 71)
                        .addComponent(btnKembali)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAir)
                    .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEs)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTotalEs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkKopi)
                            .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkJus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTea)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLemon)
                    .addComponent(txtLemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalLemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCappuccino)
                    .addComponent(txtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsActionPerformed
         txtEs.setText("5000");
    }//GEN-LAST:event_chkEsActionPerformed

    private void chkAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAirActionPerformed
       txtAir.setText("5000");

    }//GEN-LAST:event_chkAirActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void cbEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsActionPerformed
        int jumlah = (int)cbEs.getSelectedIndex();
        double harga = Double.parseDouble(txtEs.getText());
        double total = jumlah*harga;
        txtTotalEs.setText(Double.toString(total));
    }//GEN-LAST:event_cbEsActionPerformed

    private void cbLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLemonActionPerformed
        int jumlah = (int)cbLemon.getSelectedIndex();
        double harga = Double.parseDouble(txtLemon.getText());
        double total = jumlah*harga;
        txtTotalLemon.setText(Double.toString(total));
    }//GEN-LAST:event_cbLemonActionPerformed

    private void txtTotalLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalLemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalLemonActionPerformed

    private void chkKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKopiActionPerformed
        txtKopi.setText("6000");
    }//GEN-LAST:event_chkKopiActionPerformed

    private void chkJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJusActionPerformed
        txtJus.setText("12000");
    }//GEN-LAST:event_chkJusActionPerformed

    private void chkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTeaActionPerformed
        txtTea.setText("10000");
    }//GEN-LAST:event_chkTeaActionPerformed

    private void chkLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLemonActionPerformed
        txtLemon.setText("11000");
   
    }//GEN-LAST:event_chkLemonActionPerformed

    private void chkCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCappuccinoActionPerformed
        txtCappuccino.setText("12000");
    
    }//GEN-LAST:event_chkCappuccinoActionPerformed

    private void cbAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirActionPerformed
        int jumlah = (int)cbAir.getSelectedIndex();
        double harga = Double.parseDouble(txtAir.getText());
        double total = jumlah*harga;
        txtTotalAir.setText(Double.toString(total));
    }//GEN-LAST:event_cbAirActionPerformed

    private void cbKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiActionPerformed
      int jumlah = (int)cbKopi.getSelectedIndex();
        double harga = Double.parseDouble(txtKopi.getText());
        double total = jumlah*harga;
        txtTotalKopi.setText(Double.toString(total));  
    }//GEN-LAST:event_cbKopiActionPerformed

    private void cbJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusActionPerformed
        int jumlah = (int)cbJus.getSelectedIndex();
        double harga = Double.parseDouble(txtJus.getText());
        double total = jumlah*harga;
        txtTotalJus.setText(Double.toString(total));
    }//GEN-LAST:event_cbJusActionPerformed

    private void cbTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTeaActionPerformed
        int jumlah = (int)cbTea.getSelectedIndex();
        double harga = Double.parseDouble(txtTea.getText());
        double total = jumlah*harga;
        txtTotalTea.setText(Double.toString(total));
    }//GEN-LAST:event_cbTeaActionPerformed

    private void cbCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCappuccinoActionPerformed
        int jumlah = (int)cbCappuccino.getSelectedIndex();
        double harga = Double.parseDouble(txtCappuccino.getText());
        double total = jumlah*harga;
        txtTotalCappuccino.setText(Double.toString(total));
    }//GEN-LAST:event_cbCappuccinoActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
       double air = Double.parseDouble(txtTotalAir.getText());
       double es = Double.parseDouble(txtTotalEs.getText());
       double kopi = Double.parseDouble(txtTotalKopi.getText());
       double jus = Double.parseDouble(txtTotalJus.getText());
       double tea = Double.parseDouble(txtTotalTea.getText());
       double lemon = Double.parseDouble(txtTotalLemon.getText());
       double capp = Double.parseDouble(txtTotalCappuccino.getText());
       double total = air+es+kopi+jus+tea+lemon+capp;
       txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
       String total = txtTotal.getText();
       utama.setTotalMinuman(total);
       this.dispose();
      
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKopiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
                                               
      txtAir.setText("0");
      txtEs.setText("0");
      txtKopi.setText("0");
      txtJus.setText("0");
      txtTea.setText("0");
      txtLemon.setText("0");
      txtCappuccino.setText("0");
      txtTotal.setText("0");
      txtTotalAir.setText("0");
      txtTotalEs.setText("0");
      txtTotalKopi.setText("0");
      txtTotalJus.setText("0");
      txtTotalTea.setText("0");
      txtTotalLemon.setText("0");
      txtTotalCappuccino.setText("0");
      cbAir.setSelectedIndex(0);
      cbEs.setSelectedIndex(0);
      cbKopi.setSelectedIndex(0);
      cbJus.setSelectedIndex(0);
      cbTea.setSelectedIndex(0);
      cbLemon.setSelectedIndex(0);
      cbCappuccino.setSelectedIndex(0);
      chkAir.setSelected(false);
      chkEs.setSelected(false);
     chkKopi.setSelected(false);
     chkJus.setSelected(false);
     chkTea.setSelected(false);
     chkLemon.setSelected(false);
     chkCappuccino.setSelected(false);
      
      txtAir.requestFocus();
                                    
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMinuman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbAir;
    private javax.swing.JComboBox<String> cbCappuccino;
    private javax.swing.JComboBox<String> cbEs;
    private javax.swing.JComboBox<String> cbJus;
    private javax.swing.JComboBox<String> cbKopi;
    private javax.swing.JComboBox<String> cbLemon;
    private javax.swing.JComboBox<String> cbTea;
    private javax.swing.JCheckBox chkAir;
    private javax.swing.JCheckBox chkCappuccino;
    private javax.swing.JCheckBox chkEs;
    private javax.swing.JCheckBox chkJus;
    private javax.swing.JCheckBox chkKopi;
    private javax.swing.JCheckBox chkLemon;
    private javax.swing.JCheckBox chkTea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAir;
    private javax.swing.JTextField txtCappuccino;
    private javax.swing.JTextField txtEs;
    private javax.swing.JTextField txtJus;
    private javax.swing.JTextField txtKopi;
    private javax.swing.JTextField txtLemon;
    private javax.swing.JTextField txtTea;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAir;
    private javax.swing.JTextField txtTotalCappuccino;
    private javax.swing.JTextField txtTotalEs;
    private javax.swing.JTextField txtTotalJus;
    private javax.swing.JTextField txtTotalKopi;
    private javax.swing.JTextField txtTotalLemon;
    private javax.swing.JTextField txtTotalTea;
    // End of variables declaration//GEN-END:variables
}
