/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum210526;

import javax.swing.JOptionPane;

/**
 *
 * @author Khairunnisah
 */
public class FormNilai extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNilai.class.getName());

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUas = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMatkul = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        lblQuiz = new javax.swing.JLabel();
        lblTugas = new javax.swing.JLabel();
        lblUts = new javax.swing.JLabel();
        lblUas = new javax.swing.JLabel();
        txtQuiz = new javax.swing.JLabel();
        txtQuis = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtUts = new javax.swing.JTextField();
        txtUs = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        lblNilai = new javax.swing.JLabel();
        lblKonversi = new javax.swing.JLabel();
        txtNilai = new javax.swing.JTextField();
        txtKonversi = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        txtUas.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setText("FORM PENILAIAN SISWA");

        lblNama.setText("Nama Mahasiswa");

        lblKelas.setText("Kelas");

        lblMatkul.setText("Mata Kuliah");

        lblQuiz.setText("Nilai Quiz");

        lblTugas.setText("Nilai Tugas");

        lblUts.setText("Nilai Uts");

        lblUas.setText("Nilai Uas");

        btnProses.setText("Proses");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        lblNilai.setText("Nilai Akhir");

        lblKonversi.setText("Konversi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatkul)
                    .addComponent(lblQuiz)
                    .addComponent(lblKelas)
                    .addComponent(lblNama)
                    .addComponent(lblUas)
                    .addComponent(lblTugas)
                    .addComponent(lblUts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNilai)
                            .addComponent(lblKonversi))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtUs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuiz))
                            .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatkul)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProses)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuiz)
                        .addComponent(txtQuiz)
                        .addComponent(txtQuis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNilai)
                    .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTugas)
                            .addComponent(lblKonversi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUts)
                    .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String kelas = txtKelas.getText();
        String matkul = txtMatkul.getText();
        
        if(nama.isEmpty()||kelas.isEmpty()||matkul.isEmpty()){
          JOptionPane.showMessageDialog(this,"Data nama tidak boleh kosong");
          txtNama.requestFocus();
          }
        if(txtQuis.getText().isEmpty()||txtTugas.getText().isEmpty()||txtUs.getText().isEmpty()||txtUts.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Niali harus diisikan!!!");
 
        }
        else{
        try{
        double quiz  = validasiNilai(txtQuis.getText(),"QUIZ");
        double tugas =validasiNilai(txtTugas.getText(),"TUGAS");
        double uts =validasiNilai(txtUts.getText(),"UTS");
        double uas = validasiNilai(txtUs.getText(),"UAS");
        
        double na = 0.15*quiz +0.2*tugas +0.3*uts + 0.35*uas;
        
        txtNilai.setText(Double.toString(na));
        txtKonversi.setText(KonversiNilai(na));
        
        JOptionPane.showMessageDialog(this, 
                "\nNama"+nama+
                "\nKelas"+kelas+
                "\nmendapatkan nialia"+na+ "atau setara dengan"+KonversiNilai(na)+
                "\n untuk mata kuliah"+matkul,"Hasil Penilaian",JOptionPane.INFORMATION_MESSAGE    );
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Nilai harus berupa angka","Peringatan",JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Penegcekan Nilai",JOptionPane.WARNING_MESSAGE);
        }finally{
           JOptionPane.showMessageDialog(this, "Pengecekan Selesai");
        }
    }//GEN-LAST:event_btnProsesActionPerformed
    }
    private double validasiNilai(String input, String jenisNilai)throws Exception{
        double nilai = Double.parseDouble(input);
        if(nilai<0 || nilai>100)
            throw new Exception(jenisNilai+ "Harus antara 0 - 100");
        return nilai;
    }
    
    private String KonversiNilai(double nilai){
        if (nilai>=80)
            return "A";
        else if(nilai>=65)
            return "B";
        else if(nilai >= 55)
            return "C";
        else if(nilai >= 40)
            return "D";
        else
            return "E";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKonversi;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNilai;
    private javax.swing.JLabel lblQuiz;
    private javax.swing.JLabel lblTugas;
    private javax.swing.JLabel lblUas;
    private javax.swing.JLabel lblUts;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKonversi;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilai;
    private javax.swing.JTextField txtQuis;
    private javax.swing.JLabel txtQuiz;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JLabel txtUas;
    private javax.swing.JTextField txtUs;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
