/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum250626;

import javax.swing.JOptionPane;

/**
 *
 * @author Khairunnisah
 */
public class FormTravelBus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTravelBus.class.getName());

    /**
     * Creates new form FormTravelBus
     */
    public FormTravelBus() {
        initComponents();
        txtHarga.setEditable(false);
        txtTotal.setEditable(false);
        txtDiskon.setEditable(false);
        txtBayar.setEditable(false);
        txtKembalian.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupTujuan = new javax.swing.ButtonGroup();
        lblJudul = new javax.swing.JLabel();
        lblTujuan = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        rbBkt = new javax.swing.JRadioButton();
        rbSolok = new javax.swing.JRadioButton();
        rbPar = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        btnHarga = new javax.swing.JButton();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblBayar = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        lblUang = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        lblKembalian = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setText("FORM PEMBELIAN TIKET BUS");

        lblTujuan.setText("Pilihan Tujuan");

        lblKelas.setText("Pilihan Kelas");

        btnGrupTujuan.add(rbBkt);
        rbBkt.setText("Bukittinggi");

        btnGrupTujuan.add(rbSolok);
        rbSolok.setText("Solok");

        btnGrupTujuan.add(rbPar);
        rbPar.setText("Pariaman");

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan kelas", "Ekonomi", "Bisnis", "Eksekutif" }));
        cbKelas.addActionListener(this::cbKelasActionPerformed);

        btnHarga.setText("Harga 1 Tiket");
        btnHarga.addActionListener(this::btnHargaActionPerformed);

        lblJumlah.setText("Jumlah Tiket");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        lblTotal.setText("Total Harga Pembelian");

        lblDiskon.setText("Diskon");

        lblBayar.setText("Total Pembayaran");

        txtTotal.addActionListener(this::txtTotalActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(this::btnBayarActionPerformed);

        lblUang.setText("Jumlah Uang");

        txtUang.addActionListener(this::txtUangActionPerformed);

        lblKembalian.setText("Kembalian Uang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTujuan)
                            .addComponent(lblKelas)
                            .addComponent(lblJumlah))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbBkt)
                                    .addComponent(cbKelas, 0, 99, Short.MAX_VALUE)
                                    .addComponent(txtJumlah))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(rbSolok)
                                        .addGap(87, 87, 87)
                                        .addComponent(rbPar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(btnHarga)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnReset)
                                                .addGap(97, 97, 97))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(lblUang, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblKembalian))
                                                .addGap(50, 50, 50)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnKeluar)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                .addComponent(txtDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                .addComponent(txtBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                .addComponent(txtUang))))))))
                    .addComponent(lblJudul, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnBayar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblJudul)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTujuan)
                    .addComponent(rbBkt)
                    .addComponent(rbSolok)
                    .addComponent(rbPar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarga))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiskon)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBayar)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUang, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnBayar)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKelasActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        int kelas = (int)cbKelas.getSelectedIndex();
        if(!rbBkt.isSelected()&& !rbSolok.isSelected()&& !rbPar.isSelected()){
            JOptionPane.showMessageDialog(this, "Tujuan belum dipilih!!");
        }
        else if(cbKelas.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Kelas Belum dipilih!");
        }
        else{
        
        switch (kelas){
            case 1 : if(rbBkt.isSelected())
                         txtHarga.setText("40000");
                    else if(rbSolok.isSelected())
                        txtHarga.setText("25000");
                    else 
                        txtHarga.setText("15000");
                    break;
            case 2 : if(rbBkt.isSelected())
                         txtHarga.setText("75000");
                    else if(rbSolok.isSelected())
                        txtHarga.setText("55000");
                    else 
                        txtHarga.setText("40000");
                    break;  
            case 3 : if(rbBkt.isSelected())
                         txtHarga.setText("120000");
                    else if(rbSolok.isSelected())
                        txtHarga.setText("85000");
                    else 
                        txtHarga.setText("60000");
                    break;        
        }
        }
        
    }//GEN-LAST:event_btnHargaActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
      int jumlah = Integer.parseInt(txtJumlah.getText());
      if(jumlah<=0){
          JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0","Pesan kesalahan",JOptionPane.ERROR_MESSAGE);
          txtJumlah.setText("");
          txtJumlah.requestFocus();
      }
      else{
      double harga =Double.parseDouble((txtHarga.getText()));
      double total = jumlah*harga;
      double diskon =0;
      if(jumlah>=5)
          diskon = 0.1*total;
      double bayar = total - diskon;
      
      txtTotal.setText(Double.toString(total));
      txtDiskon.setText(Double.toString(diskon));
      txtBayar.setText(Double.toString(bayar));
      }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      btnGrupTujuan.clearSelection();
      cbKelas.setSelectedIndex(0);
      txtHarga.setText("");
      txtJumlah.setText("");
      txtTotal.setText("");
      txtDiskon.setText("");
      txtBayar.setText("");
      txtUang.setText("");
      txtKembalian.setText("");
      
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
     int pil = JOptionPane.showConfirmDialog(this,"Apakah ingin keluar?","Konfirmasi Keluar",JOptionPane.YES_NO_OPTION);
     
     if(pil==JOptionPane.YES_OPTION){
         System.exit(0);
     }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(txtJumlah.getText());
        double harga = Double.parseDouble(txtHarga.getText());
        double total = jumlah*harga;
        double diskon =0;
        double uang = Double.parseDouble(txtUang.getText());
       
        if(jumlah>=5)
          diskon = 0.1*total;
           double bayar = total - diskon;
           double kembali = uang - bayar;
        
        if(uang >= bayar){
            kembali = uang - bayar;
            txtKembalian.setText(Double.toString((kembali)));
        }
        else if(uang < bayar){
            JOptionPane.showMessageDialog(this,"Mohon maaf uang anda tidak cukup!!","Transaksi Gagal!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void txtUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTravelBus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.ButtonGroup btnGrupTujuan;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JLabel lblBayar;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JLabel lblUang;
    private javax.swing.JRadioButton rbBkt;
    private javax.swing.JRadioButton rbPar;
    private javax.swing.JRadioButton rbSolok;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
