/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum250626;

import javax.swing.JOptionPane;

/**
 *
 * @author Khairunnisah
 */
public class FromGajiKaryawan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromGajiKaryawan.class.getName());

    /**
     * Creates new form FromGajiKaryawan
     */
    public FromGajiKaryawan() {
        initComponents();
        txtGajiPokok.setEditable(false);
        txtUpah.setEditable(false);
        txtTotalUpah.setEditable(false);
        txtTotalGaji.setEditable(false);
        txtPajak.setEditable(false);
        txtGajiBersih.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGaji = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNik = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        cbGol = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        lblTotalUpah = new javax.swing.JLabel();
        lblTotalGaji = new javax.swing.JLabel();
        lblPajak = new javax.swing.JLabel();
        lblGajiBersih = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        txtTotalUpah = new javax.swing.JTextField();
        txtTotalGaji = new javax.swing.JTextField();
        txtPajak = new javax.swing.JTextField();
        txtGajiBersih = new javax.swing.JTextField();
        lblGajiPokok = new javax.swing.JLabel();
        lblUpah = new javax.swing.JLabel();
        txtUpah = new javax.swing.JTextField();
        txtGajiPokok = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGaji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGaji.setText("FORM PENGGAJIAN KARYAWAN");

        lblNama.setText("Nama");

        lblNik.setText("Nik");

        lblJam.setText("Jam Kerja");

        cbGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Golongan", "Golongan 1", "Golongan 2", "Golongan 3", "Golongan 4" }));

        lblTotalUpah.setText("Total Upah");

        lblTotalGaji.setText("Total Gaji");

        lblPajak.setText("Pajak");

        lblGajiBersih.setText("Gaji Bersih");

        btnHitung.setText("Hitung Gaji");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        lblGajiPokok.setText("Gaji Pokok");

        lblUpah.setText("Upah / jam");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(lblGaji))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblJam, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(137, 137, 137)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTotalGaji)
                                    .addComponent(lblGajiPokok, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(lblPajak)
                                    .addComponent(lblGajiBersih)
                                    .addComponent(lblUpah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalUpah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset)
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKeluar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalGaji, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtUpah, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtGajiPokok)
                                    .addComponent(txtPajak, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtTotalUpah))
                                .addComponent(txtGajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblGaji)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGajiPokok))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNik)
                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpah))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJam)
                            .addComponent(lblTotalUpah)
                            .addComponent(txtTotalUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalGaji)
                    .addComponent(txtTotalGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPajak))
                .addGap(18, 18, 18)
                .addComponent(btnHitung)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGajiBersih)
                    .addComponent(txtGajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnReset))
                .addGap(123, 123, 123))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
      
        try{
        int golongan =(int)cbGol.getSelectedIndex();
        String nama = txtNama.getText().trim();
        String nik = txtNik.getText().trim();
        String jam = txtJam.getText().trim();
        
        if(nama.isEmpty()){
           throw new Exception("Nama tidak boleh kosong!");
        }
        if(nik.isEmpty()){
           throw new Exception("Nik tidak boleh kosong!!");
        }
        if(!nik.matches("\\d{16}")){
           throw new Exception("NIK harus terdiri dari 16 digit angka!");
        }
         if(golongan == 0){
           throw new Exception("Pilih golongan terlebih dahulu!");
        }
        if(jam.isEmpty()){
           throw new Exception("Jam kerja tidak boleh kosong!");
        }
        int jamKerja = Integer.parseInt(jam);
        if(jamKerja <= 0){
            throw new Exception("Jam kerja harus lebih dari 0!");
        }
        
        if(jamKerja > 12){
            throw new Exception("Jam kerja tidak boleh lebih dari 12 jam!");
       }
        double gajiPokok = 0;
        double upah =  0;
        switch(golongan){
            case 1:
                gajiPokok = 2000000;
                upah = 20000;
                break;
                
            case 2:
                gajiPokok = 2750000;
                upah = 30000;
                break; 
            case 3:
                gajiPokok = 3000000;
                upah = 40000;
                break; 
            case 4:
                gajiPokok = 4500000;
                upah = 50000;
                break;   
                
        }
         double totalUpah = jamKerja * upah;
            double totalGaji = gajiPokok + totalUpah;
            double pajak = totalGaji * 0.025;
            double gajiBersih = totalGaji - pajak;
            
            txtGajiPokok.setText("Rp" +(gajiPokok));
            txtUpah.setText("Rp"+(upah));
            txtTotalUpah.setText("Rp"+(totalUpah));
            txtTotalGaji.setText("Rp" +(totalGaji));
            txtPajak.setText("Rp" + (pajak));
            txtGajiBersih.setText("Rp" +(gajiBersih));
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Jam kerja harus berupa angka!!","Error",JOptionPane.ERROR_MESSAGE);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Peringatan",JOptionPane.WARNING_MESSAGE);
        }
   

    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      txtNama.setText("");
      txtNik.setText("");
      txtJam.setText("");
      txtGajiPokok.setText("");
      txtUpah.setText("");
      txtTotalUpah.setText("");
      txtPajak.setText("");
      txtGajiBersih.setText("");
      txtTotalGaji.setText("");
       
      cbGol.setSelectedIndex(0);
      txtNama.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int pil = JOptionPane.showConfirmDialog(this,"Apakah ingin keluar?","Konfirmasi Keluar",JOptionPane.YES_NO_OPTION);
     
     if(pil==JOptionPane.YES_OPTION){
         System.exit(0);
     }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromGajiKaryawan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbGol;
    private javax.swing.JLabel lblGaji;
    private javax.swing.JLabel lblGajiBersih;
    private javax.swing.JLabel lblGajiPokok;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblPajak;
    private javax.swing.JLabel lblTotalGaji;
    private javax.swing.JLabel lblTotalUpah;
    private javax.swing.JLabel lblUpah;
    private javax.swing.JTextField txtGajiBersih;
    private javax.swing.JTextField txtGajiPokok;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtTotalGaji;
    private javax.swing.JTextField txtTotalUpah;
    private javax.swing.JTextField txtUpah;
    // End of variables declaration//GEN-END:variables
}
